intel/libyami-utils

configure.ac

To avoid add nasty version check in source code like this
https://github.com/01org/libyami-utils/blob/master/tests/vpp.cpp#L212.
We’d better check min libyami version number in configure.ac.
This will break automatic “git bisect”.However, it will keep our code more tidy.

configure.ac: check libyami version

---

examples/grid.cpp
tests/decode.cpp

Commit 8dc7783d1da6c reversed some of the changes in
commit 4ae3688ca7eb to use DynamicPointerCast instead
of std::tr1::dynamic_pointer_cast.  Libyami encapsulates
the use of ::std::tr1:: vs. ::std:: based on compiler.
Thus, use libyami's interface for this in decode.cpp.
Also, use libyami's SharedPointerCast in grid.cpp.

do not use ::std::tr1 explicitly

---

tests/vppinputoutput.cpp
tests/vppinputoutput.h
tests/vppoutputencode.cpp
tests/vppoutputencode.h
tests/yamitranscode.cpp

yamitranscode is not honoring the codec name on the command line
so it is not possible to know which codec is intended for the output
if a common extension is given. So far, common extension is ivf and it
is required that yamitranscode calls EncodeOutput->create with a codec name
for examples to run properly
supported examples below, the output file is modified on this patch. The
rest of the command line options can be modified at will
yamitranscode -i ./flambert_main.mp4_1920x1080.I420 -W 1920 -H 1080 --intraperiod 300 \
--rcmode CBR -b 2000 -o ./flambert_kfdist300_2Mbps_ytranscode.vp9
yamitranscode -i ./flambert_main.mp4_1920x1080.I420 -W 1920 -H 1080 --intraperiod 300 \
--rcmode CBR -b 2000 -o -c VP9 ./flambert_kfdist300_2Mbps_ytranscode.ivf
fixes #31 
Signed-off-by: Daniel Charles …

yamitranscode: make vp9 encoder work with yamitranscode

---

testscripts/ssim_test.py

add jpeg suffix '.mjpg' into ssim_test.py,
so that ssim_test.py can test the conformance
of those jpeg clips.

jpg_ssim: add suffix '.mjpg' into ssim_test.py

---

tests/encode.cpp

When we have b frame, encoder will cache some frame to adjust reference order.
We need flush them, else we will lost frame

tests: encode, flush frame at eos

---

tests/decodeoutput.cpp

error return from function was not correctly describing the function
being called
Signed-off-by: Daniel Charles <daniel.charles@intel.com>

decodeoutput: fix typo on error return from function

---

tests/vppinputasync.h
tests/vppinputdecode.cpp
tests/vppinputoutput.cpp
tests/vppinputoutput.h
tests/vppoutputencode.cpp
tests/yamitranscode.cpp

Implement 10 bits-depth transcoding.
Command line parameter "-s" is just used to set input file's fourcc in case fourcc of input file can not be guessed via its extra name.

Yamitrans hevc10bit

---

tests/encode.cpp
tests/encodeinput.cpp

re-alloc a new bigger output buffer for the encoded picture size is
larger than the default.
to fix issue [#657](https://github.com/01org/libyami/issues/657)

enc: resize output buffer size

---

tests/decodeoutput.cpp
tests/vppinputoutput.h

Implement picture area copying according to the crop information,
for yuv file writing, MD5 calculating and displaying.
Because if the src fourcc is equal to the dst fourcc, the function
vpp->process() will not be called.
to fix [VIZ-8821](https://jira01.devtools.intel.com/browse/VIZ-8821)

yamidecode: copy yuv data according to crop infor

---

tests/decodeinputavformat.cpp

The old version ffmpeg does't support HEVC, and does't have the API
av_packet_unref(). So add some MACRO to make yami-utils can be compatible
with all the version of FFMPEG.
to fix #73 

avformat: be compatible with all version ffmpeg

---

README.md

add two label for build and coverity in README.md.
to implement [VIZ-9125](https://jira01.devtools.intel.com/browse/VIZ-9125) based on Yizhou's code.

README: add coverity label

---

tests/Makefile.am
tests/V4L2Device.cpp
tests/V4L2Device.h
tests/V4L2Renderer.cpp
tests/V4L2Renderer.h
tests/decodehelp.cpp
tests/v4l2decode.cpp
vaapi/vaapidisplay.h

The main target of this pull request is enabling zero copy feature in v4l2decoder. But it does more things beyond this. Current v4l2decoder is a little mess. It full of duplicate and full of #ifdef. It's hard to make it even buildable. So before I add zero copy patch. I use some patch to refact the v4l2decoder to make it more readable.

Use zero copy api in v4l2 decoder

---

tests/V4L2Renderer.cpp
tests/V4L2Renderer.h
tests/v4l2decode.cpp

1, define the base class's destructor as virtual.
2, make sure the pointer is not NULL before accessing.
to fix static code scan issue.

v4l2: add virtual destructor and check NULL point

---

tests/decode.cpp
tests/decodehelp.cpp
tests/decodehelp.h
tests/vppinputdecode.cpp
tests/vppinputdecode.h

Supporting svc-t decodeing for vp8 with max-layer 3.

vp8dec: enable svc-t decoding

---

tests/decode.cpp
tests/decodehelp.cpp

If std::string was set with 0, it can't be assigned a new
value on Ubuntu Trusty.
to fix issue [94](https://github.com/01org/libyami-utils/issues/94)

yamidecode: avoid using memset to reset "std::string"

---

tests/decodeoutput.cpp

m_file member pointer is not initialized and will get an arbitrary
value.  If that arbitrary value is not 0, then it fools code like
"if(m_file)" into thinking it's ok to use m_file.
Thus, ensure m_file is initialized to NULL in constructor.
Fixes 01org/libyami#743

tests/decodeoutput: initialize m_file pointer to NULL

---

tests/V4L2Renderer.cpp
tests/V4L2Renderer.h
tests/v4l2decode.cpp

when we got resolution change notification, we need
1. drain output
2. reallocate surfaces.
3. stream off/on the output

v4l2: handle on fly resolution change.

---

tests/encodehelp.h
tests/yamitranscode.cpp

JPEG has different quality range than other codecs.
For issue 01org/libyami#769 and pull-request 01org/libyami#803

Update quality-level cmdline option description

---

tests/encodeinput.cpp

In yamiencode, add time stamp into every frame of vp8/vp9 stream files.
To fix issue [#800](https://github.com/01org/libyami/issues/800)
Signed-off-by: dongping wu <dongpingx.wu@intel.com>

vpx_enc: set time stamp into every frame

---

tests/decodeinputavformat.cpp

av_register_all was deprecated in FFMPEG commit
0694d8702421e7aff1340038559c438b61bb30dd
It is no longer necessary to call av_register_all after
this commit.
Fixes #117

decode avformat: av_register_all is deprecated since 58.9.100

---

tests/decodeinputavformat.cpp

LIBAVFORMAT_VERSION_INT should be checked instead of
LIBAVCODEC_VERSION_INT for av_register_all deprecation
since versions could differ.

decode avformat: use LIBAVFORMAT_VERSION_INT instead

---

configure.ac
tests/Makefile.am
tests/decodeoutput.cpp
tests/md5.c
tests/md5.h

Android does not have libbsd. so we need use built-in md5 calculator.

add built in md5 sum calculator. 

---

configure.ac
examples/Makefile.am
tests/Makefile.am

Due to the flags SDL required for Linux again, we need add these flags for SDL signoff called SDL325 - Compile With Defenses Enabled

Add flags for SDL signoff called SDL325 - Compile With Defenses Enabled

---

configure.ac
tests/decodeinputavformat.cpp

If we know we got a entire frame, we can pass the flag to decoder to tell them stop search for next frame. this need work with https://github.com/intel/libyami/pull/849

Fix low latency

---

examples/androidplayer.cpp
examples/simpleplayer.cpp
tests/decodecapi.c
tests/encodeInputDecoder.cpp
tests/v4l2decode.cpp
tests/vppinputdecode.cpp
tests/vppinputdecodecapi.cpp

libyami introduced VIDEO_DECODE_BUFFER_FLAG_FRAME_END and
uses it in avc/hevc decoder to stop frame decoding in
some cases.  Thus, it is necessary to properly initialize
the VideoDecodeBuffer so that VIDEO_DECODE_BUFFER_FLAG_FRAME_END
is not erroneously and arbitrarily set.
Fixes #134

Properly initialize VideoDecodeBuffer
